"""
Generated Project

Represents a project generated by the AutoBot Assembly System.
"""

from dataclasses import dataclass
from typing import List, Optional, Dict, Any
from enum import Enum
from pathlib import Path


class ProjectType(str, Enum):
    APPLICATION = "application"
    LIBRARY = "library"
    WEB_SERVICE = "web_service"
    CLI_TOOL = "cli_tool"


@dataclass
class ProjectStructure:
    entry_points: List[str]
    source_directories: List[str]
    config_files: List[str]
    test_directories: List[str]


@dataclass
class GeneratedProject:
    """Represents a generated project with all necessary metadata."""
    
    project_name: str
    project_path: str
    language: str
    project_type: ProjectType
    dependencies: List[str]
    structure: ProjectStructure
    build_commands: Optional[List[str]] = None
    run_commands: Optional[List[str]] = None
    files: Optional[Dict[str, str]] = None
    metadata: Optional[Dict[str, Any]] = None
